"""Extract structured Character, WorldRule and Relationship records from a book outline.

Takes the free-text book outline generated by OutlineGenerator and runs an
LLM extraction pass that returns JSON suitable for bulk-insert into the
characters, world_rules and relationships tables.
"""

from __future__ import annotations

import json
import logging

from app.services.model_router import get_model_router

logger = logging.getLogger(__name__)

SETTINGS_EXTRACTOR_SYSTEM = """你是小说设定编辑。从用户提供的全书大纲中，提取结构化数据。只输出一个 JSON 对象，不要 markdown、不要解释。

JSON 结构：
{
  "characters": [
    {
      "name": "角色名",
      "identity": "身份标签（一句）",
      "age": "年龄（可空）",
      "gender": "性别（可空）",
      "appearance": "外貌关键点",
      "background": "出身与成长（2-4 句）",
      "personality": "性格内核",
      "motivation": "核心动机",
      "fears": "最恐惧或最在意之物",
      "key_trauma": "关键创伤事件（如果大纲提到）",
      "signature_dialogue": "代表性对白（如果大纲提到）",
      "abilities": [
        {"stage": "卷数或阶段", "description": "能力/境界", "cost": "代价或副作用"}
      ],
      "relationships": [
        {"target": "另一角色名", "type": "敌人/盟友/师徒/恋人/竞争者", "note": "简述"}
      ]
    }
  ],
  "world_rules": [
    {
      "category": "geography|history|religion|politics|economy|culture|magic_system|race|artifact|faction",
      "rule_text": "完整的设定描述（不要省略细节）"
    }
  ],
  "relationships": [
    {
      "source_name": "源角色名（必须出现在 characters 中）",
      "target_name": "目标角色名",
      "rel_type": "ally|enemy|mentor|lover|rival|family|other",
      "label": "关系描述短语，如 宿敌 / 生死之交",
      "note": "可选长描述（1-2 句背景、演变、代价）",
      "sentiment": "positive|negative|neutral"
    }
  ]
}

规则：
- characters 必须覆盖大纲里所有被点名的主要角色，不要遗漏
- 若大纲没有给出某个字段的信息，填空字符串或省略该键，不要编造
- world_rules 每条 category 只能是上面列出的枚举之一
- world_rules 要覆盖大纲里所有明确提到的地理、历史、宗教、政治、经济、文化、力量体系、种族、法宝、势力等内容
- world_rules 要拆成多条，单条只讲一件事；不要把整段塞成一条
- relationships 必须覆盖大纲里所有明显的人物关系；单条关系只填一次，不要 A→B 和 B→A 重复同内容（除非关系是单向的，比如单恋）
- relationships 的 source_name/target_name 必须和 characters[].name 字面一致
- relationships.rel_type 只能是上面列出的枚举之一"""


async def extract_settings_from_outline(outline_text: str) -> dict:
    """Run the LLM to extract characters + world rules + relationships JSON.

    Returns a dict with 'characters', 'world_rules', 'relationships' keys
    (each a list). Returns empty lists on parse failure rather than raising.
    """
    router = get_model_router()
    messages = [
        {"role": "system", "content": SETTINGS_EXTRACTOR_SYSTEM},
        {"role": "user", "content": f"大纲原文：\n\n{outline_text}"},
    ]
    try:
        result = await router.generate(task_type="extraction", messages=messages)
        text = result.text.strip()
    except Exception as e:
        logger.warning("Settings extraction LLM call failed: %s", e)
        return {"characters": [], "world_rules": [], "relationships": []}

    # Strip possible markdown fences
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        logger.warning("Settings extraction JSON parse failed: %s; head=%r", e, text[:200])
        return {"characters": [], "world_rules": [], "relationships": []}

    chars = data.get("characters") if isinstance(data, dict) else None
    rules = data.get("world_rules") if isinstance(data, dict) else None
    rels = data.get("relationships") if isinstance(data, dict) else None
    return {
        "characters": chars if isinstance(chars, list) else [],
        "world_rules": rules if isinstance(rules, list) else [],
        "relationships": rels if isinstance(rels, list) else [],
    }
