"""add llm_endpoints table

Revision ID: 5feb9a2cff43
Revises: c7cdeccaf965
Create Date: 2026-04-15 15:55:46.267980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5feb9a2cff43'
down_revision: Union[str, Sequence[str], None] = 'c7cdeccaf965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model_configs', sa.Column('endpoint_id', sa.UUID(), nullable=True))
    op.add_column('model_configs', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('model_configs', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.alter_column('model_configs', 'model_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_unique_constraint(None, 'model_configs', ['task_type'])
    op.create_foreign_key(None, 'model_configs', 'llm_endpoints', ['endpoint_id'], ['id'], ondelete='SET NULL')
    op.drop_column('model_configs', 'provider')
    op.drop_column('model_configs', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_configs', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_configs', type_='foreignkey')
    op.drop_constraint(None, 'model_configs', type_='unique')
    op.alter_column('model_configs', 'model_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('model_configs', 'max_tokens')
    op.drop_column('model_configs', 'temperature')
    op.drop_column('model_configs', 'endpoint_id')
    op.drop_table('llm_endpoints')
    # ### end Alembic commands ###
