"""Export endpoints -- render a project as EPUB / PDF / DOCX.

All three routes stream the generated bytes back with a
``Content-Disposition: attachment`` header so browsers download the file
directly.
"""

from __future__ import annotations

import logging
import urllib.parse
import uuid

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.services.export_service import export_project

router = APIRouter(prefix="/api/export", tags=["export"])
logger = logging.getLogger(__name__)


def _content_disposition(filename: str) -> str:
    # RFC 5987 encoding so non-ASCII (e.g. Chinese) titles survive headers.
    quoted = urllib.parse.quote(filename)
    return f"attachment; filename=\"{quoted}\"; filename*=UTF-8''{quoted}"


async def _render(
    project_id: uuid.UUID,
    fmt: str,
    db: AsyncSession,
) -> Response:
    try:
        data, filename, mime = await export_project(db, project_id=project_id, fmt=fmt)
    except LookupError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        logger.exception("export %s failed for project %s: %s", fmt, project_id, exc)
        raise HTTPException(status_code=500, detail=f"export failed: {exc}")
    return Response(
        content=data,
        media_type=mime,
        headers={"Content-Disposition": _content_disposition(filename)},
    )


@router.get("/projects/{project_id}.epub")
async def export_epub(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "epub", db)


@router.get("/projects/{project_id}.pdf")
async def export_pdf(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "pdf", db)


@router.get("/projects/{project_id}.docx")
async def export_docx(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "docx", db)
