"""Export endpoints -- render a project as EPUB / PDF / DOCX / TXT.

All routes stream the generated bytes back with a
``Content-Disposition: attachment`` header so browsers download the file
directly.
"""

from __future__ import annotations

import logging
import re
import urllib.parse
import uuid

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.services.export_service import (
    _load_project_tree,
    _ordered_chapters,
    _safe_filename,
    export_project,
)

router = APIRouter(prefix="/api/export", tags=["export"])
logger = logging.getLogger(__name__)


def _content_disposition(filename: str) -> str:
    # RFC 5987 encoding so non-ASCII (e.g. Chinese) titles survive headers.
    quoted = urllib.parse.quote(filename)
    return f"attachment; filename=\"{quoted}\"; filename*=UTF-8''{quoted}"


async def _render(
    project_id: uuid.UUID,
    fmt: str,
    db: AsyncSession,
) -> Response:
    try:
        data, filename, mime = await export_project(db, project_id=project_id, fmt=fmt)
    except LookupError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        logger.exception("export %s failed for project %s: %s", fmt, project_id, exc)
        raise HTTPException(status_code=500, detail=f"export failed: {exc}")
    return Response(
        content=data,
        media_type=mime,
        headers={"Content-Disposition": _content_disposition(filename)},
    )


@router.get("/projects/{project_id}.epub")
async def export_epub(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "epub", db)


@router.get("/projects/{project_id}.pdf")
async def export_pdf(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "pdf", db)


@router.get("/projects/{project_id}.docx")
async def export_docx(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    return await _render(project_id, "docx", db)


# ---------------------------------------------------------------------------
# TXT (legado-friendly plain text)
# ---------------------------------------------------------------------------
# Chapter titles produced by generation are usually bare ("开端"); prefix them
# with 第N章 so legado's chapter-split regex works. Titles that already carry
# the prefix are kept as-is to avoid "第1章 第1章 开端".
_CHAPTER_PREFIX_RE = re.compile(r"^第[0-9零一二两三四五六七八九十百千万]+章")


def _build_txt_bytes(project) -> bytes:
    parts: list[str] = []
    for _vol, ch in _ordered_chapters(project):
        title = (ch.title or "").strip()
        if title and _CHAPTER_PREFIX_RE.match(title):
            heading = title
        elif title:
            heading = f"第{ch.chapter_idx}章 {title}"
        else:
            heading = f"第{ch.chapter_idx}章"
        body = (ch.content_text or "").replace("\r\n", "\n").strip("\n")
        parts.append(f"{heading}\n\n{body}\n")
    return "\n".join(parts).encode("utf-8")


@router.get("/projects/{project_id}.txt")
async def export_txt(project_id: uuid.UUID, db: AsyncSession = Depends(get_db)) -> Response:
    try:
        project = await _load_project_tree(db, project_id)
        data = _build_txt_bytes(project)
    except LookupError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:
        logger.exception("export txt failed for project %s: %s", project_id, exc)
        raise HTTPException(status_code=500, detail=f"export failed: {exc}")
    filename = _safe_filename(project.title or str(project.id), "txt")
    return Response(
        content=data,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": _content_disposition(filename)},
    )
